void _puts_recursion(char *s);
int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int func_alt(int n, int a);
int is_palindrome(char *s);
int _strlen(char *s);
int find_pal(char *s, int start, int end);
int is_prime_number(int n);
int _num_pr(int n, int b);
